force-app/main/default/objects/Book__c/fields/Number_of_Books_Available__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Books_Available__c</fullName>
    <description>Number of books available for loan</description>
    <label>Number of Books Available</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Number_of_Books_Loaned_Out__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Books_Loaned_Out__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of books currently loaned out</description>
    <label>Number of Books Loaned Out</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox indicating if the loan is still active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Date_Loaned__c.field-meta.xml
<CustomField>
    <fullName>Date_Loaned__c</fullName>
    <defaultValue>today()</defaultValue>
    <description>Date for when the book was loaned out</description>
    <label>Date Loaned</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Date_Returned__c.field-meta.xml
<CustomField>
    <fullName>Date_Returned__c</fullName>
    <description>Date the book was returned</description>
    <label>Date Returned</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Reader__c.field-meta.xml
<CustomField>
    <fullName>Reader__c</fullName>
    <label>Reader</label>
    <referenceTo>Reader__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reader__c/Reader__c.object-meta.xml
<CustomObject>
    <label>Reader</label>
    <nameField>
        <label>Reader Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Readers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reader__c/fields/Number_of_Books_Borrowed__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Books_Borrowed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of books that they are borrowing</description>
    <label>Number of Books Borrowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reader__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Subject that the Revol specializes in</description>
    <label>Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanAfterInsert_Test.cls
@isTest
private class LoanAfterInsert_Test {
	@isTest
    private static void verifyLoanAfter(){

        //load test data
        Book__c b = new Book__c(
        	Name = 'Test Book',
            Subject__c = 'AWS',
            Number_of_Books_Available__c = 100,
            Number_of_Books_Loaned_Out__c = 0
        );
        insert b;
        
        Reader__c r = new Reader__c(
        	Name = 'Test Reader',
            Subject__c = 'AWS',
            Number_of_Books_Borrowed__c = 0
        );
        insert r;
        
        Loan__c loan = new Loan__c(
        	Name = 'Test Loan',
            Book__c = b.Id,
            Reader__c = r.Id,
            Date_Loaned__c = date.today(),
            Active__c = True
        ); 
        
        insert loan;
        
        //verify results
        Test.startTest();
        	loan.Date_Returned__c = date.today();
        	loan.Active__c = False;
        
        	//update loan to trigger after update handler
        	update loan;
        	
        	//verify happy path results
        	Book__c bCheck = [SELECT Id, Number_of_Books_Available__c, Number_of_Books_Loaned_Out__c FROM Book__c WHERE Id = :b.id];
        	System.assertEquals(0, bCheck.Number_of_Books_Loaned_Out__c);
        	System.assertEquals(100, bCheck.Number_of_Books_Available__c);
        
        	//verify sad path results
        	DmlException dmlError;
        	
        	loan.Active__c = False;
        	loan.Date_Returned__c = null;
        	try{
                update loan;
            }catch(DmlException d){
                dmlError = d;
            }
        	System.assertEquals('An in-active loan must have an return date!', dmlError.getDmlMessage(0));
        
        	loan.Active__c = True;
        	loan.Date_Returned__c = date.today();
			try{
                update loan;
            }catch(DmlException d){
                dmlError = d;
            }
        	System.assertEquals('An active loan cannot have a return date!', dmlError.getDmlMessage(0));
        
        Test.stopTest();
    }
}