force-app/main/default/objects/Book__c/fields/Number_of_Books_Available__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Books_Available__c</fullName>
    <description>Number of books available for loan</description>
    <label>Number of Books Available</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Number_of_Books_Loaned_Out__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Books_Loaned_Out__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of books currently loaned out</description>
    <label>Number of Books Loaned Out</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Reader__c.field-meta.xml
<CustomField>
    <fullName>Reader__c</fullName>
    <label>Reader</label>
    <referenceTo>Reader__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reader__c/Reader__c.object-meta.xml
<CustomObject>
    <label>Reader</label>
    <nameField>
        <label>Reader Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Readers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reader__c/fields/Number_of_Books_Borrowed__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Books_Borrowed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of books that they are borrowing</description>
    <label>Number of Books Borrowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reader__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Subject that the Revol specializes in</description>
    <label>Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanBeforeInsert_Test.cls
@isTest
private class LoanBeforeInsert_Test {
	@isTest
    private static void verifyLoanBefore(){
        //update list
        List<Book__c> testBooks = new List<Book__c>();
        
        //load test data
        Book__c b = new Book__c(
        	Name = 'Test Book',
            Subject__c = 'AWS',
            Number_of_Books_Available__c = 100,
            Number_of_Books_Loaned_Out__c = 0
        );
        testBooks.add(b);
        
         Book__c b2 = new Book__c(
        	Name = 'Test Book',
            Subject__c = 'Salesforce',
            Number_of_Books_Available__c = 100,
            Number_of_Books_Loaned_Out__c = 0
        );
        
        testBooks.add(b2);
        
        Book__c b3 = new Book__c(
        	Name = 'Test Book',
            Subject__c = 'AWS',
            Number_of_Books_Available__c = 0,
            Number_of_Books_Loaned_Out__c = 0
        );
        
        testBooks.add(b3);
        insert testBooks;
        
        Reader__c r = new Reader__c(
        	Name = 'Test Reader',
            Subject__c = 'AWS',
            Number_of_Books_Borrowed__c = 0
        );
        insert r;
        
        Loan__c loan = new Loan__c(
        	Name = 'Test Loan',
            Book__c = b.Id,
            Reader__c = r.Id
        ); 
        
        Loan__c loan2 = new Loan__c(
        	Name = 'Test Loan2',
            Book__c = b2.Id,
            Reader__c = r.Id
        ); 
        
        Loan__c loan3 = new Loan__c(
        	Name = 'Test Loan3',
            Book__c = b3.Id,
            Reader__c = r.Id
        ); 
        
        //verify results
        Test.startTest();
        	insert loan;
        	
        	//check happy path of successful insert
        	Book__c bCheck = [SELECT Id, Number_of_Books_Available__c, Number_of_Books_Loaned_Out__c FROM Book__c WHERE Id = :b.id];
        	System.assertEquals(1, bCheck.Number_of_Books_Loaned_Out__c);
        	System.assertEquals(99, bcheck.Number_of_Books_Available__c);
        	
        	//check sad path of unsuccessful inserts
        	DmlException dmlError;
        	try{
                insert loan2;
            }catch (DmlException d){
                dmlError = d;
            }
        	
        	System.assertEquals('Subject of Book and Reader must be the same!', dmlError.getDmlMessage(0));
        
        	try{
                insert loan3;
            }catch (DmlException d){
                dmlError = d;
            }
        	
        	System.assertEquals('There are no copies of that book available!', dmlError.getDmlMessage(0));
        Test.stopTest();
    }
}